### ISSUE TITLE
Optimize (Product) Category Dropdown

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/electricity-prices-switzerland#55]
Discussed at the workshop on 10.01.2023: It is hard for users outside of elcom to understand the different product categories H and C. Even though the information is offered by clicking on the info Icon, it is still challenging to map that information to the dropdown. 

A possible idea would be to introduce a hierachy with a tree in the dropwdown. 
Another possibility would be to make the text for the individual elements in the dropdown more descriptive. However, we will need to consider the width of the dropdown menu element with this apprach. The wording / text needs to work/fit for all locales  (DE, FR, IT). 

In a first step, we will prepare a design suggestion to present to the client. 

![Image](https://user-images.githubusercontent.com/29289679/212031631-c3d94d2f-6bd6-4db6-978a-f593a20e790d.png)

**Comment by sosiology** [comment]
Suggestion looks good, but also needs to also be applied to the "Detail pages" not only the landing page

**Comment by AnninaWalker** [comment]
LGTM!

**Comment by ptbrowne** [comment]
@sosiology I put your last comment in a new issue, the rest is implemented and deployed.
