### ISSUE TITLE
Add Legend to the Cards on Detail Pages

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/electricity-prices-switzerland#56]
Add the median legend to all charts on the detail page cards so the user has a reference. Currently the legend is only on the "Kantonsvergleich" but should also be added to the card "Preisverteilung in der Schweiz"

![Image](https://user-images.githubusercontent.com/29289679/212635461-274f5837-664d-4be7-810b-7c5963e7b1e1.png)

**Comment by AnninaWalker** [comment]
There is some layout overlap on the leftside

![Image](https://user-images.githubusercontent.com/59613691/212648265-3dd07216-8a64-402f-92fd-3c1c161a3340.png)

**Comment by ptbrowne** [comment]
Fixed and deployed.
