### ISSUE TITLE
Optimize highlighting of selected municipalities

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/electricity-prices-switzerland#57]
Currently when a  municipality is hovered on in the list on the right sidebar it is highlighted on the map. In some cases, where there are many small municipalities (for example in Thurgau), this is not sufficient/hard for the user to see. To make it more obvious, implement a tooltip on the map in addition to the highlight to allow the user to locate the municipality faster on the map.

**Comment by AnninaWalker** [comment]
LGTM!
