### ISSUE TITLE
Add mean to the tooltip on the map

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/electricity-prices-switzerland#59]
On the display of the map of Switzerland with the municipalities, the most expensive network operator is shown in the max. and min. median legend in each case, not the most expensive municipality. This is somewhat confusing. 

We will suppliment the information in the tooltip on the map showing the mean in the case of multiple providors by adding a third "chip". To support the user to understand that municipaliities can have multiple NBs and that the values in the rows are the mean. 

We will implement the solution, after which it will be reviewed and the design adjusted as needed.

**Comment by ptbrowne** [comment]
Implemented and deployed.
